plugins:
  literatecomputing_notice_enabled:
    default: true
    client: true
    hidden: true
  lc_show_header:
    default: true
    client: true
    hidden: false
  lc_hide_admin_list:
    default: pfaffman
    client: true
    hidden: true